---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Check Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Show Nginx configuration status
  debug:
    msg: "{{ nginx_test.stderr_lines }}"
